apiVersion: apps/v1
kind: Deployment
metadata:
  name: capacity-reporting
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: capacity-reporting
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'c3psnow'
        vault.hashicorp.com/agent-inject-secret-api: 'concourse/main/capacity-report'
        vault.hashicorp.com/agent-inject-template-api: |
          {{- with secret "concourse/main/capacity-report" -}}
            export API_KEY_NOCO="{{ .Data.data.noco_api_key }}"
            export URL="{{ .Data.data.noco_url }}"
            export API_KEY="{{ .Data.data.api_key }}"
          {{- end }}
      labels:
        app: capacity-reporting
    spec:
      containers:
        - image: registry.quokka.ninja/ccfs/capacity-reporting:0.0.7
          name: capacity-reporting
          args: ['/bin/bash', '-c', 'source /vault/secrets/api && uvicorn NocoDB:app --host 0.0.0.0 --port 8000 --root-path /capacityReporting']
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: gitlab-cr
